import Script from 'next/script';

export default function Head() {
  return (
    <head>
      <title>유튜브 썸네일 다운로드</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" />
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css" />
      {/* 카카오 */}
      <Script src="https://developers.kakao.com/sdk/js/kakao.js" async />
      <link rel="icon" href="/favicon.ico" />
    </head>
  )
}
